version: "3.9"
services: 
  rethinkdb:
    image: rethinkdb:2.4.1
    restart: always
    ports: 
      - 8080:8080
      - 28015:28015
      - 29015
    networks: 
      - spotchat

networks: 
  spotchat: